### PR TITLE
[WIP] switch to pug

### LINKED ISSUE #57: jadeをpugにする

### PR DESCRIPTION
**Pull request by otofune**
resolve #57.

### CODE REVIEW

**Comment by otofune** [comment]
still WIP

**Comment by Petitsurume** [comment]
image
why dont use?

**Comment by otofune** [comment]
@Petitsurume what, edit button? Do you suggest me to use edit button on GitHub UI? I can edit things on my machines and remote servers. it's probably no needed.

**Comment by Petitsurume** [comment]
@otofune I suggest adding [WIP] to the beginning of issue title

**Comment by otofune** [comment]
@Petitsurume ah, okay. i'll do it soon

**Pull request closed without merging**
